### ISSUE TITLE
Can't remove links

### ISSUE THREAD

**Issue by HoogieHar** [djmadeira/lightweight-new-tab-page#1]
I just installed this extension and LOVE it, but 2 links I added the first time around keep coming back, even though I keep deleting them. The next time I open the new tab page they're back, and at the very top of my links list. Is there something I can do to remove them permanently? Thanks!

**Comment by sinterstice** [comment]
Hey, it's awesome that somebody else is using this! I wrote this a while ago and it's pretty poorly written and doesn't have any tests. This could be a pretty good excuse to refactor it in something modern.

I've tried fresh-installing the extension and I'm not seeing what you describe. Can you try fresh installing? Sorry I can't give you a better solution.

**Comment by HoogieHar** [comment]
I've done so and it's good.  I was just hoping to not have to re-do all of my links.  But no big deal.  Thanks!
